@startuml
skinparam linetype ortho

title Block View Level 3

package LaymanDeploy {

    package DeployModule {
        component PluginRepositoryAdapter
        component Orchestrator
        component PluginAdapter
        component KubernetesAdapter
    }
    
}

package Kubernetes {
    artifact Service
}

database PluginRepository
database ExternalStorage


WebInterface --> Orchestrator: Deploy/Configure Plugin
Orchestrator --> PluginRepositoryAdapter: Get Plugin
PluginRepositoryAdapter --> PluginRepository: Get Plugin
Orchestrator --> PluginAdapter: Create Plugin Adapter
PluginAdapter --> Service: Interface provider
Orchestrator --> KubernetesAdapter: Deploy Plugin
KubernetesAdapter --> PluginAdapter: Get Config
KubernetesAdapter ---> Kubernetes: Deploy Plugin


@enduml