@startuml

actor User
package "LaymanDeploy" {
    component "Web Interface"
    component "Backend Service"
}

component "Kubernetes" as Kubernetes {
    artifact "Service" as Service
}

database GitRepository
database ExternalStorage

User --> [Web Interface]: Interact
[Web Interface] --> [Backend Service]: Control

[Backend Service] --> Service: Collect data
[Backend Service] --> ExternalStorage: Store data

[Backend Service] --> Service: Monitor
[Backend Service] --> [Web Interface]: Information

[Backend Service] --> GitRepository: Get plugin definitions
[Backend Service] --> Service: Deploy services

@enduml
