@startuml
skinparam linetype ortho

title Block View Level 3

package LaymanDeploy {

    package DeployModule {
        component Plugin
        component Orchestrator
        component PluginAdapter
        component KubernetesAdapter
    }
    
}

package Kubernetes {
    artifact Service
}

database PluginRepository


WebInterface --> Orchestrator: Deploy/Configure Plugin
Orchestrator -> Plugin: Get Plugin
WebInterface ----> Plugin: Validate Plugin
Plugin --> PluginRepository: Get Plugin
Orchestrator --> PluginAdapter: Create Plugin Adapter
PluginAdapter --> Service: Interface provider
Orchestrator --> KubernetesAdapter: Deploy Plugin
KubernetesAdapter --> PluginAdapter: Get Config
KubernetesAdapter ---> Kubernetes: Deploy Plugin


@enduml